services:
  api:
    image: polylend-api
    container_name: polylend-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: ['node', 'build/api.js']
  listener:
    image: polylend-listener
    container_name: polylend-listener
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: ['node', 'build/listener.js']
  caddy:
    image: caddy
    container_name: polylend-caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
